# Generated by Django 3.0.8 on 2021-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor', '0002_auto_20210317_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='conference',
            field=models.CharField(default='iclr18', max_length=30),
            preserve_default=False,
        ),
    ]
