# Generated by Django 3.0.8 on 2021-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor', '0003_review_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='forum_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
