# Generated by Django 3.0.8 on 2021-04-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=30)),
                ('example_index', models.IntegerField()),
                ('forum_id', models.CharField(max_length=30)),
                ('review_id', models.CharField(max_length=30)),
                ('rebuttal_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('reviewer', models.CharField(max_length=30)),
                ('interleaved_index', models.IntegerField()),
                ('num_rebuttal_sentences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RebuttalSentenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=30)),
                ('rebuttal_id', models.CharField(max_length=30)),
                ('rebuttal_sentence_index', models.IntegerField()),
                ('initials', models.CharField(max_length=4)),
                ('is_valid', models.BooleanField()),
                ('aligned_review_sentences', models.CharField(max_length=50)),
                ('relation_label', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('alignment_category', models.CharField(max_length=200)),
                ('errors', models.CharField(max_length=200)),
                ('time_to_annotate', models.IntegerField()),
                ('start_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=30)),
                ('overall_comment', models.CharField(max_length=30)),
                ('is_valid', models.BooleanField()),
                ('errors', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=4)),
                ('time_to_annotate', models.IntegerField()),
                ('start_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSentenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=30)),
                ('review_sentence_index', models.IntegerField()),
                ('initials', models.CharField(max_length=4)),
                ('labels', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=30)),
                ('sentence_idx', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('suffix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orda.Example')),
            ],
        ),
    ]
