# Generated by Django 3.0.8 on 2021-04-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='sentence_idx',
            new_name='sentence_index',
        ),
    ]
