# Generated by Django 3.0.8 on 2021-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orda', '0003_auto_20210412_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewannotation',
            name='errors',
            field=models.CharField(max_length=500),
        ),
    ]
