# Generated by Django 3.0.8 on 2021-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orda', '0004_auto_20210413_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
