# Generated by Django 3.0.8 on 2021-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_align', '0002_text_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentannotation',
            name='dataset',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedpair',
            name='dataset',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
