# Generated by Django 3.0.8 on 2021-01-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_align', '0003_auto_20210107_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentannotation',
            name='example_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotatedpair',
            name='example_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
