# Generated by Django 3.0.8 on 2021-01-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_align', '0004_auto_20210108_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignmentannotation',
            name='review_sentence_idx',
        ),
        migrations.AddField(
            model_name='alignmentannotation',
            name='aligned_review_sentences',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
