# Generated by Django 3.0.8 on 2021-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_align', '0005_auto_20210108_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedpair',
            name='forum_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
