# Generated by Django 3.0.8 on 2021-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator_initials', models.CharField(max_length=4)),
                ('dataset', models.CharField(max_length=30)),
                ('example_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=30)),
                ('example_index', models.IntegerField()),
                ('forum_id', models.CharField(max_length=30)),
                ('review_sid', models.CharField(max_length=30)),
                ('rebuttal_sid', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('reviewer', models.CharField(max_length=30)),
                ('rebuttal_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PairAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebuttal_sid', models.CharField(max_length=30)),
                ('annotator_initials', models.CharField(max_length=4)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sid', models.CharField(max_length=30)),
                ('sentence_idx', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('suffix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebuttal_sid', models.CharField(max_length=30)),
                ('rebuttal_sentence_idx', models.IntegerField()),
                ('annotator_initials', models.CharField(max_length=4)),
                ('is_valid', models.BooleanField()),
                ('aligned_review_sentences', models.CharField(max_length=50)),
                ('relation_label', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('alignment_errors', models.CharField(max_length=200)),
            ],
        ),
    ]
