# Generated by Django 3.0.8 on 2021-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewannotation',
            name='initials',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
