# Generated by Django 3.0.8 on 2021-04-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zune', '0002_reviewannotation_initials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rebuttalsentenceannotation',
            old_name='time_of_submission',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='reviewannotation',
            old_name='time_of_submission',
            new_name='start_time',
        ),
    ]
