# Generated by Django 3.0.8 on 2021-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='review_sid',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
