# Generated by Django 3.0.8 on 2021-03-14 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_quality', '0002_annotation_review_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='constructive',
            new_name='constructiveness',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='strengths_weaknesses',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='useful_comments',
            new_name='presentation',
        ),
        migrations.AddField(
            model_name='annotation',
            name='meta_review',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='reproducibility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
